# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Exposer main CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test exposer-core
      run: >
        ./gradlew exposer-core:test 
        -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}
    - name: Test exposer-spring-boot-autoconfigure
      run: >
        ./gradlew exposer-spring-boot-autoconfigure:test 
        -PsonatypeUsername=${{ secrets.SONATYPE_USERNAME }} -PsonatypePassword=${{ secrets.SONATYPE_PASSWORD }}
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: "exposer-core/build/reports/jacoco/test/jacocoTestReport.xml,\
          exposer-spring-boot-autoconfigure/build/reports/jacoco/test/jacocoTestReport.xml"
